#!/bin/sh


echo Content-type: text/html
echo
echo "#########################################################"
echo "<br>"
echo "Mysql connection checking script"   
echo "<br>"
echo "#########################################################"
echo "<br>"
echo "<br>"

 db_user=`echo "$QUERY_STRING" | cut -f1 -d'&' | sed "s|user=||"`
       db_password=`echo "$QUERY_STRING" | cut -f2 -d'&' | sed "s|pass=||"`
#echo $db_user
#echo $db_password


RESULT=`mysql --user="$db_user" --password="$db_password" --skip-column-names -e "SHOW DATABASES LIKE 'mysql'"` 2> /dev/null
if [ $RESULT ]; then
    echo ""
    echo "Username and password match"
    a=2
    break


else
    echo "" 
    echo "Username and password doesn't match"
fi





